#!/usr/bin/env python3
"""Build the installable web app (PWA) into docs/ from catan-third-hand.html.

    python3 build_standalone.py            # writes docs/
    cd docs && python3 -m http.server 8000 # try it at http://localhost:8000

Serve docs/ from any static host over https (GitHub Pages: Settings → Pages → /docs) and use
Share → Add to Home Screen on iPhone/iPad, or Safari → File → Add to Dock on a Mac.
"""
import hashlib, json, os, re
from PIL import Image, ImageDraw

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "docs")
os.makedirs(OUT, exist_ok=True)
src = open(os.path.join(HERE, "catan-third-hand.html"), encoding="utf-8").read()

# --- icons: teal tile, white hexagon, two dice pips ---
def icon(size):
    im = Image.new("RGB", (size, size), "#146b64")
    d = ImageDraw.Draw(im)
    import math
    cx = cy = size / 2; r = size * 0.34
    pts = [(cx + r * math.cos(math.radians(-90 + 60 * k)), cy + r * math.sin(math.radians(-90 + 60 * k))) for k in range(6)]
    d.polygon(pts, fill="#f2ead6", outline="#ffffff")
    pr = size * 0.045
    for dx, dy in [(-0.11, -0.05), (0.11, 0.05), (0.0, 0.0)]:
        x, y = cx + dx * size, cy + dy * size
        d.ellipse([x - pr, y - pr, x + pr, y + pr], fill="#b23b2e" if (dx, dy) == (0.0, 0.0) else "#2b2926")
    return im
for name, size in [("icon-512.png", 512), ("icon-192.png", 192), ("apple-touch-icon.png", 180)]:
    icon(size).save(os.path.join(OUT, name))

# --- index.html: the app wrapped in a real document with PWA / iOS metadata ---
body = src.replace("<title>Catan Third Hand</title>", "", 1)
head = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>Catan Third Hand</title>
<link rel="manifest" href="manifest.webmanifest">
<link rel="apple-touch-icon" href="apple-touch-icon.png">
<meta name="theme-color" content="#146b64">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-title" content="Third Hand">
<meta name="apple-mobile-web-app-status-bar-style" content="default">
<meta name="color-scheme" content="light dark">
<style>html{-webkit-text-size-adjust:100%} body{margin:0;padding:env(safe-area-inset-top) env(safe-area-inset-right) env(safe-area-inset-bottom) env(safe-area-inset-left)}</style>
</head><body>
"""
sw_reg = """
<script>
if("serviceWorker" in navigator && location.protocol!=="file:"){
  window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(()=>{}));
}
</script>
</body></html>
"""
body = re.sub(r"\s*</body>\s*</html>\s*$", "", body)      # the artifact file may already carry its own closers
html = head + body + sw_reg
open(os.path.join(OUT, "index.html"), "w", encoding="utf-8").write(html)

# --- manifest + service worker (offline app shell; cache name changes with every build) ---
json.dump({
    "name": "Catan Third Hand", "short_name": "Third Hand",
    "description": "A companion board so a bot can play the third seat in your two-person Catan game.",
    "start_url": "./", "scope": "./", "display": "standalone",
    "background_color": "#eef1ee", "theme_color": "#146b64",
    "icons": [{"src": "icon-192.png", "sizes": "192x192", "type": "image/png"},
              {"src": "icon-512.png", "sizes": "512x512", "type": "image/png", "purpose": "any maskable"}],
}, open(os.path.join(OUT, "manifest.webmanifest"), "w"), indent=2)
ver = hashlib.sha1(html.encode()).hexdigest()[:10]
open(os.path.join(OUT, "sw.js"), "w").write(f"""// generated by build_standalone.py
const CACHE = "third-hand-{ver}";
const SHELL = ["./", "index.html", "manifest.webmanifest", "icon-192.png", "icon-512.png", "apple-touch-icon.png"];
self.addEventListener("install", e => e.waitUntil(caches.open(CACHE).then(c => c.addAll(SHELL)).then(() => self.skipWaiting())));
self.addEventListener("activate", e => e.waitUntil(
  caches.keys().then(ks => Promise.all(ks.filter(k => k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim())));
self.addEventListener("fetch", e => {{
  const req = e.request;
  if (req.method !== "GET" || new URL(req.url).origin !== location.origin) return;
  // the page itself: network first (so updates show on the very next launch), saved copy only when offline
  if (req.mode === "navigate" || req.destination === "document") {{
    e.respondWith(fetch(req, {{cache: "no-cache"}}).then(res => {{
      const copy = res.clone(); caches.open(CACHE).then(c => c.put("index.html", copy)); return res;
    }}).catch(() => caches.match("index.html")));
    return;
  }}
  e.respondWith(caches.match(req).then(hit => hit || fetch(req).then(res => {{
    if (res.ok) {{ const copy = res.clone(); caches.open(CACHE).then(c => c.put(req, copy)); }}
    return res;
  }})));
}});
""")
print("built docs/ — version", ver, "—", len(html)//1024, "KB")
